name: Run Montrek TestSuite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "00 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  run-tests:
    uses: montrek-software/.github/.github/workflows/montrek_tests_template.yml@main
    with:
      montrek_base_version: ${{ vars.MONTREK_BASE_VERSION }}
      montrek_project: ${{ vars.MONTREK_PROJECT }}
    secrets:
      PAT: ${{ secrets.ECONOMIC_COMMON_PAT }}
